version: "3.7"

# compose a local container

services:
  dreamspell-app:
    image: dreamspell-app
    container_name: dreamspell-app
    build: .
    ports:
      - "80:80"
    networks:
      - frontend

networks:
  frontend:
